spring:
  application:
    name: slave
eureka:
  instance:
    hostname: localhost
    metadata-map:
      instanceId: slave ${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
